version: "3.2"

services:
  resident-information-api:
    image: resident-information
    build:
      context: ResidentInformationApi/
      dockerfile: ./Dockerfile
    ports:
      - 3000:3000

  resident-information-api-test:
    image: resident-information-api-test
    build:
      context: .
      dockerfile: ResidentInformationApi.Tests/Dockerfile
